<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PunchSync.Application\PunchSync.Application.csproj" />
    <ProjectReference Include="..\PunchSync.Domain\PunchSync.Domain.csproj" />
    <ProjectReference Include="..\PunchSync.Infra\PunchSync.Infra.csproj" />
  </ItemGroup>

</Project>
